In [2]:
%load_ext autoreload
%autoreload 2
import unittest 
import sys
import os

sys.path.append(os.getcwd() + '/..')

from backend.AppApi import *

In [3]:
import numpy as np
import pandas as pd
from Constants import Const
import matplotlib.pyplot as plt

In [4]:
#this loads in the processed dataset, does some cleaning, adds in some dose thresholds, and parses the string lists into actual lists
data = load_dose_symptom_data(use_lstm=False, file='./merge_df_20260421.csv')
data

,id,volume,mean_dose,min_dose,max_dose,V5,V10,V15,V20,V25,...,total_mean_dose,Parotid_Gland_limit,IPC_limit,IPC_limit2,MPC_limit,MPC_limit2,SPC_limit,SPC_limit2,Larynx_limit,Esophagus_limit
0,STIEFEL_24,"[14724.42626953125, 14765.625, 6632.9956054687...","[22.765716284275324, 33.629034598214275, 56.96...","[1.0, 2114.0, 4179.0, 3625.0, 3459.0, 2969.0, ...","[4362.0, 3864.0, 6126.0, 7216.0, 5552.0, 5877....","[80.0625, 100.0, 100.0, 100.0, 100.0, 100.0, 1...","[70.3125, 100.0, 100.0, 100.0, 100.0, 100.0, 1...","[64.75, 100.0, 100.0, 100.0, 100.0, 100.0, 100...","[61.5, 100.0, 100.0, 100.0, 100.0, 100.0, 100....","[58.03125, 98.5, 100.0, 100.0, 100.0, 100.0, 1...",...,1795.847534,True,True,False,True,False,True,False,False,False
1,STIEFEL_26,"[10428.309631347656, 17159.777069091797, 4182....","[19.083991985203443, 21.81411015361559, 48.068...","[352.0, 572.0, 909.0, 3685.0, 599.0, 609.0, 38...","[3401.0, 3709.0, 5978.0, 7046.0, 3621.0, 4159....","[95.4375, 100.0, 100.0, 100.0, 100.0, 100.0, 1...","[61.53125, 78.6875, 99.9375, 100.0, 48.46875, ...","[55.34375, 75.625, 99.75, 100.0, 24.296875, 33...","[49.1875, 70.625, 99.0625, 100.0, 18.40625, 22...","[44.75, 47.5, 98.75, 100.0, 5.3359375, 16.25, ...",...,1790.729475,True,True,False,True,True,True,True,True,False
2,STIEFEL_28,"[10272.979736328125, 21972.10121154785, 10272....","[33.69805989786887, 20.803234820775426, 33.698...","[1075.0, 754.0, 1075.0, 1075.0, 532.0, 484.0, ...","[5966.0, 3283.0, 5966.0, 5966.0, 3305.0, 5288....","[100.0, 100.0, 100.0, 100.0, 100.0, 98.5, 100....","[100.0, 95.0, 100.0, 100.0, 33.375, 42.9375, 6...","[96.5, 79.875, 96.5, 96.5, 15.3671875, 34.4062...","[86.1875, 62.75, 86.1875, 86.1875, 8.390625, 2...","[73.4375, 27.28125, 73.4375, 73.4375, 3.335937...",...,1208.798443,True,False,False,False,False,False,False,False,False
3,STIEFEL_34,"[16405.33447265625, 21472.7783203125, 13253.63...","[27.220497237569013, 29.323211818879553, 40.88...","[307.0, 2155.0, 594.0, 1120.0, 3675.0, 3087.0,...","[5181.0, 4611.0, 7108.0, 5900.0, 6108.0, 6322....","[91.5625, 100.0, 100.0, 100.0, 100.0, 100.0, 1...","[75.1875, 100.0, 85.8125, 100.0, 100.0, 100.0,...","[68.9375, 100.0, 79.9375, 94.9375, 100.0, 100....","[64.6875, 100.0, 74.6875, 88.6875, 100.0, 100....","[60.84375, 81.8125, 69.1875, 83.9375, 100.0, 1...",...,2039.120846,True,True,True,True,True,True,True,True,False
4,STIEFEL_36,"[7168.5791015625, 15391.845703125, 1870.422363...","[13.436689655172408, 21.328410064239833, 43.44...","[594.0, 559.0, 3332.0, 3958.0, 678.0, 688.0, 4...","[2900.0, 3511.0, 4613.0, 5788.0, 3779.0, 4840....","[100.0, 100.0, 100.0, 100.0, 100.0, 100.0, 100...","[42.8125, 66.625, 100.0, 100.0, 52.65625, 77.0...","[34.53125, 64.625, 100.0, 100.0, 36.21875, 59....","[29.25, 63.0625, 100.0, 100.0, 24.796875, 45.4...","[20.859375, 60.125, 100.0, 100.0, 16.15625, 36...",...,1596.746221,True,True,False,True,False,True,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
332,STIEFEL_1115,"[8907.16552734375, 17410.58349609375, 8565.216...","[23.911040703052716, 33.06531945101748, 33.098...","[244.0, 2074.0, 236.0, 1588.0, 2279.0, 1813.0,...","[4173.0, 4071.0, 5901.0, 5939.0, 4870.0, 4722....","[87.25, 100.0, 89.75, 100.0, 100.0, 100.0, 100...","[78.75, 100.0, 77.6875, 100.0, 100.0, 100.0, 1...","[71.8125, 100.0, 64.3125, 100.0, 100.0, 100.0,...","[67.0625, 100.0, 59.34375, 96.9375, 100.0, 95....","[63.5, 78.3125, 57.375, 91.9375, 98.6875, 58.6...",...,1536.966028,True,False,False,False,False,True,False,False,False
333,STIEFEL_1118,"[11671.600341796875, 17134.552001953125, 8338....","[0.5289939992940343, 3.861663861505167, 1.2593...","[4.0, 22.0, 4.0, 15.0, 270.0, 189.0, 236.0, 25...","[343.0, 768.0, 479.0, 1906.0, 630.0, 489.0, 14...","[0.0, 41.46875, 0.0, 63.90625, 11.9921875, 0.0...","[0.0, 0.0, 0.0, 43.28125, 0.0, 0.0, 9.5078125,...","[0.0, 0.0, 0.0, 23.484375, 0.0, 0.0, 0.0, 20.4...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.52929687...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...",...,231.598743,False,False,False,False,False,False,False,False,False
334,STIEFEL_1120,"[10272.979736328125, 18988.9102935791, 10272.9...","[33.69805989786887, 17.399674961909618, 33.698...","[1075.0, 667.0, 1075.0, 1075.0, 1080.0, 883.0,...","[5966.0, 2879.0, 5966.0, 5966.0, 3725.0, 5677....","[100.0, 100.0, 100.0, 100.0, 100.0, 100.0, 100...","[100.0, 93.75, 100.0, 100.0, 100.0, 99.1875, 9...","[96.5, 63.0625, 96.5, 96.5, 60.96875, 58.90625...","[86.1875, 32.0, 86.1875, 86.1875, 26.828125, 3...","[73.4375, 8.2578125, 73.4375, 73.4375, 12.5468...",...,1206.610169,True,False,False,False,False,False,False,False,False
335,STIEFEL_1126,"[10272.979736328125, 16794.204711914062, 10272...","[33.69805989786887, 0.0, 33.69805989786887, 33...","[1075.0, 1.0, 1075.0, 1075.0, 1.0, 1.0, 1.0, 1...","[5966.0, 0.0, 5966.0, 5966.0, 63.0, 45.0, 987....","[100.0, 0.0, 100.0, 100.0, 0.0, 0.0, 10.453125...","[100.0, 0.0, 100.0, 100.0, 0.0, 0.0, 0.0, 0.30...","[96.5, 0.0, 96.5, 96.5, 0.0, 0.0, 0.0, 0.0, 0....","[86.1875, 0.0, 86.1875, 86.1875, 0.0, 0.0, 0.0...","[73.4375, 0.0, 73.4375, 73.4375, 0.0, 0.0, 0.0...",...,129.810371,False,False,False,False,False,False,False,False,False
336,STIEFEL_1130,"[7704.16259765625, 23784.027099609375, 9117.27...","[2.3335882352941186, 7.0501836133726, 12.15950...","[9.0, 45.0, 15.0, 21.0, 591.0, 464.0, 743.0, 1...","[1607.0, 1248.0, 3594.0, 3458.0, 2805.0, 2757....","[17.109375, 80.4375, 64.4375, 67.375, 100.0, 9...","[4.70703125, 13.109375, 58.375, 26.25, 70.8125...","[0.427734375, 0.0, 47.4375, 12.53125, 36.8125,...","[0.0, 0.0, 21.640625, 7.97265625, 12.8515625, ...","[0.0, 0.0, 9.3984375, 3.9296875, 2.142578125, ...",...,706.013871,False,False,False,False,False,False,False,False,False

In [5]:
#see AppApi.add_confunder_dose_limits for the <Organ>_limit at the end
#based on rules in literature cited in the paper
for col in data.columns:
    #skip similar values for the symptoms ect
    if 'symptoms' in col and 'drymouth' not in col:
        continue
    if len(col) == 3 and col[0] in ['V','D']:
        continue
    print(col,data[col].iloc[0])
    print()

id STIEFEL_24

volume [14724.42626953125, 14765.625, 6632.99560546875, 6645.355224609375, 4412.384033203125, 10765.228271484375, 4927.3681640625, 2138.214111328125, 28690.7958984375, 33988.95263671875, 18489.990234375, 105266.87622070312, 1668.548583984375, 69827.72827148438, 13220.672607421875, 8486.9384765625, 31360.4736328125, 88099.365234375, 2377.166748046875, 62589.111328125, 21600.494384765625, 13150.634765625, 10522.15576171875, 37012.939453125, 31022.64404296875, 21130.828857421875, 21802.3681640625, 4037.4755859375, 12231.903076171875, 35962.371826171875, 64290.618896484375, 6723.6328125, 5903.778076171875, 16689.605712890625, 188521.27075195312, 108229.06494140625, 5170.440673828125, 6822.509765625, 8021.392822265625, 902.252197265625]

mean_dose [22.765716284275324, 33.629034598214275, 56.96660869565216, 55.531078735275855, 43.19306255835666, 41.684462303865246, 50.74464046822744, 58.88312138728324, 23.921418724870758, 41.066468632552706, 45.61051247771827, 69.07339164807641, 51.254197530864154, 34.839220012980114, 57.37862262387028, 35.26666019417477, 26.606764319495436, 57.25845819304146, 27.88954939341421, 20.785825434439136, 61.61570093457944, 55.41979949874686, 30.611585747846494, 25.49595503116655, 55.03363883231502, 59.88494443361281, 71.11955782312928, 60.4485102040816, 57.72683058268769, 56.79111123840079, 48.01430054469713, 59.63676470588249, 54.321193300767625, 55.680222167366054, 49.23548678948386, 38.143899124476654, 28.3738406374502, 27.06176328502415, 17.7860811504879, 29.097534246575332]

min_dose [1.0, 2114.0, 4179.0, 3625.0, 3459.0, 2969.0, 3668.0, 5568.0, 489.0, 2726.0, 2720.0, 4085.0, 3508.0, 713.0, 2928.0, 1355.0, 801.0, 1633.0, 1591.0, 652.0, 5274.0, 2789.0, 1021.0, 661.0, 2820.0, 5567.0, 6425.0, 5761.0, 3934.0, 3338.0, 2476.0, 3999.0, 4240.0, 3839.0, 1634.0, 858.0, 1544.0, 1707.0, 752.0, 2733.0]

max_dose [4362.0, 3864.0, 6126.0, 7216.0, 5552.0, 5877.0, 6710.0, 6908.0, 3679.0, 6298.0, 7181.0, 7473.0, 6967.0, 7377.0, 7213.0, 5639.0, 6678.0, 7222.0, 3740.0, 7143.0, 7292.0, 6105.0, 5448.0, 5279.0, 7046.0, 6998.0, 7325.0, 7251.0, 6077.0, 6141.0, 6307.0, 6766.0, 6047.0, 6353.0, 6720.0, 7139.0, 5179.0, 3480.0, 2921.0, 3156.0]

V5 [80.0625, 100.0, 100.0, 100.0, 100.0, 100.0, 100.0, 100.0, 99.8125, 100.0, 100.0, 100.0, 100.0, 100.0, 100.0, 100.0, 100.0, 100.0, 100.0, 100.0, 100.0, 100.0, 100.0, 100.0, 100.0, 100.0, 100.0, 100.0, 100.0, 100.0, 100.0, 100.0, 100.0, 100.0, 100.0, 100.0, 100.0, 100.0, 100.0, 100.0]

D2 [39.96875, 38.0625, 60.90625, 71.8125, 52.15625, 55.6875, 63.5, 67.125, 35.3125, 60.15625, 69.5, 73.3125, 69.3125, 72.375, 70.25, 54.3125, 59.40625, 71.25, 35.6875, 65.6875, 72.375, 60.125, 51.71875, 46.3125, 66.0625, 66.75, 72.625, 71.8125, 60.21875, 60.53125, 60.6875, 65.6875, 60.09375, 61.6875, 61.25, 64.9375, 47.3125, 33.46875, 27.078125, 31.3125]

D5 [38.6875, 37.625, 60.625, 71.0625, 50.75, 53.84375, 60.875, 64.125, 34.6875, 59.1875, 66.375, 72.8125, 65.25, 71.875, 68.25, 52.78125, 52.8125, 69.75, 34.75, 60.28125, 71.9375, 59.6875, 50.125, 42.875, 63.71875, 64.75, 72.4375, 69.5625, 59.75, 60.3125, 60.03125, 64.8125, 59.71875, 60.53125, 60.375, 61.0, 42.6875, 32.5625, 25.703125, 30.96875]

n_stage n2b

is_ajcc_8th_edition False

baseline_mbs_digest nan

performance_score 1

ic 0.0

hpv 0.0

t_stage t0

rt 1.0

chemotherapy concurrent_chemotherapy

M6_mbs_digest 2.0

concurrent 1.0

subsite NOS

followup_days 1201.0

is_male True

age 48.0

os 1.0

dates [0, 1, 2, 3, 4, 5, 6, 7, 13, 33, 59, 85, 268]

t4 0

n3 0

BOT 0

Tonsil 0

old 0

digest_increase 0

symptoms_drymouth [2.0, 4.0, 5.0, 8.0, 2.0, 2.0, 3.0, 6.0, 8.0, 8.0, 8.0, 3.0, 0.0]

total_mean_dose 1795.8475344954259

Parotid_Gland_limit True

IPC_limit True

IPC_limit2 False

MPC_limit True

MPC_limit2 False

SPC_limit True

SPC_limit2 False

Larynx_limit False

Esophagus_limit False

In [6]:
Const.organ_list

['Esophagus',
 'Spinal_Cord',
 'Lt_Brachial_Plexus',
 'Rt_Brachial_Plexus',
 'Cricopharyngeal_Muscle',
 'Cricoid_cartilage',
 'IPC',
 'MPC',
 'Brainstem',
 'Larynx',
 'Thyroid_cartilage',
 'Rt_Sternocleidomastoid_M',
 'Rt_Mastoid',
 'Rt_Parotid_Gland',
 'Rt_Medial_Pterygoid_M',
 'Rt_Lateral_Pterygoid_M',
 'Rt_Masseter_M',
 'Lt_Sternocleidomastoid_M',
 'Lt_Mastoid',
 'Lt_Parotid_Gland',
 'Lt_Submandibular_Gland',
 'Lt_Medial_Pterygoid_M',
 'Lt_Lateral_Pterygoid_M',
 'Lt_Masseter_M',
 'Supraglottic_Larynx',
 'SPC',
 'Rt_Submandibular_Gland',
 'Hyoid_bone',
 'Soft_Palate',
 'Genioglossus_M',
 'Tongue',
 'Rt_Ant_Digastric_M',
 'Lt_Ant_Digastric_M',
 'Mylogeniohyoid_M',
 'Extended_Oral_Cavity',
 'Mandible',
 'Hard_Palate',
 'Lower_Lip',
 'Upper_Lip',
 'Glottic_Area']

In [7]:
#clustering works conceptuallby be selecting a set of dose/organ features and a set of organs,
#and converting that into a 1d vector for each patient ,which is input into cluster
def to_value_array(df,features,organ_subset):
    organ_positions = [Const.organ_list.index(o) for o in organ_subset]
    vals = np.stack(df[features].apply(lambda x: np.stack([np.array([ii[i] for i in organ_positions]).astype(float) for ii in x]).ravel(),axis=1).values)
    return vals

to_value_array(data,features=['V15','V25'],organ_subset=['IPC','MPC','SPC'])

array([[100.        , 100.        , 100.        , 100.        ,
        100.        , 100.        ],
       [100.        , 100.        , 100.        , 100.        ,
        100.        , 100.        ],
       [ 34.59375   ,  84.8125    ,  98.5625    ,  21.078125  ,
         61.46875   ,  72.        ],
       ...,
       [ 45.4375    ,  53.90625   ,  90.0625    ,  14.0390625 ,
         29.5625    ,  71.1875    ],
       [  0.        ,   0.        ,   0.        ,   0.        ,
          0.        ,   0.        ],
       [ 50.625     , 100.        ,  93.1875    ,   7.19140625,
         80.0625    ,  86.1875    ]])

In [8]:
#clustering is done in the add_sd_dose_clusters in appAPi
#this does the function of to_value_array and then runs clustering on the data
#by default, we use a gaussian mixture model
#this returns a dataframe with a 'dose_clusters' column with the cluster labels
clusters = add_sd_dose_clusters(data,
                     features=['V15','V25'], #dose features e.g. VX, DX, mean_dose, volume
                     organ_subset=['IPC','MPC','SPC'], #organs to use in clustering
                     n_clusters=7, #number of clusters
                     normalize=True #whether to normalize the input data
                    )
clusters[['id','dose_clusters']].iloc[0:10]

           id  dose_clusters
0  STIEFEL_24              6
1  STIEFEL_26              6
2  STIEFEL_28              2
3  STIEFEL_34              6
4  STIEFEL_36              6
5  STIEFEL_38              5
6  STIEFEL_42              5
7  STIEFEL_45              6
8  STIEFEL_47              6
9  STIEFEL_54              6

In [12]:
#clusters are ordered by mean_dose in reorder_clusters column (change the "by" argument to reorder clusters to change)
#this orders by the average number of people with t3 or t4
reorder_clusters(clusters,'dose_clusters',by='t_severe')[['id','dose_clusters']].iloc[0:10]

KeyError: 't_severe'

In [9]:
#We can also add in custom clustering and reducers
#reducers are e.g. dimensionality reduction done before the clustering
#reduers may also work with an autoencoder if you add a wrapper function to work with reducer.fit_transform(numpy_array)
from sklearn.decomposition import PCA

#see keyword_clusterer to see predefned cluster options
add_sd_dose_clusters(data,
                     clusterer=keyword_clusterer('kmeans',6),
                     reducer=PCA(3),
                     features=['V15','V25'], #dose features e.g. VX, DX, mean_dose, volume
                     organ_subset=['IPC','MPC','SPC'], #organs to use in clustering
                     normalize=True #whether to normalize the input data
                    )[['id','dose_clusters']].iloc[0:10]

           id  dose_clusters
0  STIEFEL_24              5
1  STIEFEL_26              5
2  STIEFEL_28              2
3  STIEFEL_34              5
4  STIEFEL_36              5
5  STIEFEL_38              4
6  STIEFEL_42              4
7  STIEFEL_45              4
8  STIEFEL_47              5
9  STIEFEL_54              5

In [10]:
#we can preform likelihood ratio tests with the clusters and confounders for different binary symptom outcomes.
#this returns the dataframe with columns with results in the form 'cluster_<symptom>_<threshold>_<timepoint>' for each option tested
lrt_results = get_cluster_lrt(clusters,
                              symptoms=['drymouth'], #symptoms to test
                              confounders=['t4','n3'], #confounders to use in the lrt test
                              nWeekList=[[13,33]], #list of sets of week. we take the max over each list, so this is max drymouth between 6 weeks and 6 months post treatment
                              thresholds=[5]) #severity thresholds totest
lrt_results[['dose_clusters']+[c for c in lrt_results if 'cluster_drymouth_5_33wks' in c]].groupby('dose_clusters').first()

/Users/siyuanzhao/Documents/GitHub/QubbedDataAnalysis/python/../backend/AppApi.py:301: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '0.9830961445252652' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  df.loc[df[in_clust].index,[colname+'_'+name]] = res[name]
/Users/siyuanzhao/Documents/GitHub/QubbedDataAnalysis/python/../backend/AppApi.py:301: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '-0.021592655248091647' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  df.loc[df[in_clust].index,[colname+'_'+name]] = res[name]
/Users/siyuanzhao/Documents/GitHub/QubbedDataAnalysis/python/../backend/AppApi.py:301: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '0.9827728924302418' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  df.loc[df[in_clust].index,[colname+'_'+name]] = res[name]
/Users/siyuanzhao/Documents/GitHub/QubbedDataAnalysis/python/../backend/AppApi.py:301: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '1.9995510929738884' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  df.loc[df[in_clust].index,[colname+'_'+name]] = res[name]
/Users/siyuanzhao/Documents/GitHub/QubbedDataAnalysis/python/../backend/AppApi.py:301: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '0.9963561051516663' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  df.loc[df[in_clust].index,[colname+'_'+name]] = res[name]

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4, 5, 6]

In [ ]:
#This section deals with rule explainers

In [11]:
#this processes the data into inputs in terms of dose featuers and outcomes
temp_x, temp_y = get_rule_inference_data(clusters,
                                         ['IPC','SPC'], #organs for inputs to consider
                                         ['drymouth'], #outcomes to consider
                                         ['V25','V30','mean_dose'],
                                         [13,33],
                                         include_limits=True)
temp_x.head()

,V25_IPC,V25_SPC,V30_IPC,V30_SPC,mean_dose_IPC,mean_dose_SPC,Parotid_Gland_limit,IPC_limit,IPC_limit2,MPC_limit,MPC_limit2,SPC_limit,SPC_limit2,Larynx_limit,Esophagus_limit
0,100.000000,100.0,100.000000,100.00000,50.744640,59.884944,1,1,0,1,0,1,0,0,0
1,100.000000,100.0,100.000000,100.00000,52.224735,67.431397,1,1,0,1,1,1,1,1,0
2,21.078125,72.0,16.765625,61.28125,17.433103,43.319443,1,0,0,0,0,0,0,0,0
3,100.000000,100.0,100.000000,100.00000,64.008076,70.848023,1,1,1,1,1,1,1,1,0
4,100.000000,100.0,100.000000,100.00000,52.122804,57.250228,1,1,0,1,0,1,0,0,0

In [12]:
temp_y.head()

   drymouth
0       8.0
1       5.0
2       3.0
3       2.0
4       3.0

In [13]:
#this generates a set of rules. second input is assumed to be a binary dataframe, but can technically have any integer input
#here we're generating rules to predict if a patient has drymouth (this is an option in the interface)
temprules = get_rule_df(temp_x,pd.DataFrame(temp_y > 5))
for k,v in temprules[0].items():
    print(k,v)
    print()

features ['V25_IPC']

thresholds [np.float64(44.0)]

splits [0       True
1       True
2      False
3       True
4       True
       ...
332     True
333    False
334    False
335    False
336    False
Name: V25_IPC, Length: 337, dtype: bool]

rule 0       True
1       True
2      False
3       True
4       True
       ...
332     True
333    False
334    False
335    False
336    False
Name: V25_IPC, Length: 337, dtype: bool

info 0.011082168383014096

odds_ratio 1.5078958024024836

lower_count 98

lower_tp 31

lower_mean 0.3163265306122449

upper_count 239

upper_tp 114

upper_mean 0.4769874476987448

In [14]:
#for generating rule explanations we actually use cluster membership 
#this tests all splits and save the memories and stuff lol
cluster_outcome = clusters.dose_clusters.apply(lambda x: x == clusters.dose_clusters.max())
cluster_rules = get_rule_df(temp_x,pd.DataFrame(cluster_outcome))
[[k['features'],k['thresholds'],k['info']] for k in cluster_rules[0:4]]

[[['V25_IPC'], [np.float64(2.0)], np.float64(0.05072207786747429)],
 [['V25_IPC'], [np.float64(4.0)], np.float64(0.05805909385694952)],
 [['V25_IPC'], [np.float64(6.0)], np.float64(0.060529211180099185)],
 [['V25_IPC'], [np.float64(8.0)], np.float64(0.07561588446184622)]]

In [15]:
#This is a version of the AppApi call that gets the rules to return to the interface, in case you want to generate those,
#The difference here is that in the AppAPI the cluster labels and arguments are passed as a json file in the request

#this returns of list of dictionaries with information about the rules
def get_rules(df,
                   organs=Const.organ_list[:],#organs to check
                   symptoms=['drymouth'],#symptom to check. I forget why it's a list and not just one
                   organ_features=['V5','V10','V15','V20','V25','V30','V35','V40','V45','V50','V55','V60','V65','V70','V75','V80','mean_dose','max_dose'],
                   s_dates=[33],
                   threshold=5, #threshold for the rule. e.g. we want to predict symptoms[0] > threshold
                   maxdepth=3,#max number of thresholds
                   min_odds=0,#used to trim the forward search
                   min_info=.08,#used to trim the forward search
                   criteria='info',#criteria used to chose rules, info or odds_ratio. odds_ratio is only positive
                   max_rules=4,#max number of rule sets to return
                   max_frontier=10,#used to trim forward search. 
                   granularity=1,#how granular to go in the splits (e.g. every 1 rad, every .1 rads
                   predict_cluster = -1,#if 1 or true, predict the cluster membership. otherwise we use the symptoms
                   cluster=None,
                   use_limits=False#wether to use dose limits in addition to the other stuff idk
             ):
    df.post_cluster = df.dose_clusters
    df = df.set_index('id')
    if predict_cluster is not None and predict_cluster >= 0:
        cluster = None
    dose_df, outcome_df = get_rule_inference_data(
            df,
            organs,
            symptoms,
            organ_features,
            s_dates,
            cluster=cluster,
            include_limits=use_limits,
        )
    symptom_bool = (outcome_df>=threshold)
    if predict_cluster is not None and predict_cluster >= 0:
        df['temp_outcome'] = df.post_cluster.apply(lambda x: x == predict_cluster)
        y = df[['temp_outcome']]
    else:
        y = symptom_bool
    rules = get_rule_df(dose_df,y,min_odds=min_odds,granularity=granularity)
    sort_rules = lambda rlist: sorted(rlist, key=lambda x: -x[criteria])
    rules = sort_rules(rules)
    min_info = min(rules[0].get('info',0.0)*.6,float(min_info))
    rules = [r for r in rules if r.get('info',0) >= min_info]
    if len(rules) > 800:
        rules = rules[:800]
    print('n rules',len(rules))
    frontier = [None]
    best_rules = []
    depth = 0
    while (depth < maxdepth) and (frontier is not None) and (len(frontier) > 0):
        frontier = get_best_rules(frontier,rules,y,min_odds=min_odds,criteria=criteria)
        frontier = sorted(frontier, key = lambda x: -x[criteria] if x is not None else 0)
        frontier = frontier[:max_frontier]
        depth += 1
        best_rules.extend(frontier)
        print('lb',len(best_rules))
        print()
    
    best_rules = sort_rules(best_rules)
    best_rules = best_rules[:max_rules]
    best_rules = joblib.Parallel(n_jobs=-2)(joblib.delayed(format_rule_json)((br,y,symptom_bool)) for br in best_rules)
    print([(r['features'],r.get('info')) for r in best_rules])
    pos_ids = y[y.values.astype(bool)].index.values.tolist()    
    for br in best_rules:
        br['target_ids'] = pos_ids
    return best_rules
    
test_rules = get_rules(clusters)
print(len(test_rules),'rules generated')
best_rule = test_rules[0]
print('best rule for predicting drymouth > 5 of the selected organs')
print('with a mutual information score with target outcome of ',best_rule['info'])
for organ,threshold in zip(best_rule['features'],best_rule['thresholds']):
    print(organ + ' > ' + str(threshold))

/var/folders/pm/_db3z8953vb1gtk99jkk_sb80000gn/T/ipykernel_32448/51819337.py:22: UserWarning: Pandas doesn't allow columns to be created via a new attribute name - see https://pandas.pydata.org/pandas-docs/stable/indexing.html#attribute-access
  df.post_cluster = df.dose_clusters

n rules 218
lb 3

lb 6

lb 7

[(['V35_Thyroid_cartilage', 'V20_Brainstem', 'max_dose_Brainstem'], np.float64(0.043844526073811924)), (['V35_Thyroid_cartilage', 'max_dose_Brainstem'], np.float64(0.040161598141544685)), (['V35_Thyroid_cartilage', 'V20_Brainstem'], np.float64(0.0389617597355556)), (['V25_Brainstem', 'max_dose_Brainstem'], np.float64(0.032069074662777475))]
4 rules generated
best rule for predicting drymouth > 5 of the selected organs
with a mutual information score with target outcome of  0.043844526073811924
V35_Thyroid_cartilage > 50.0
V20_Brainstem > 17.0
max_dose_Brainstem > 2977.0

In [19]:
with open("20260421_rules.json", "w") as f:
    json.dump(test_rules, f, indent=4, default=lambda x: int(x) if isinstance(x, np.integer) else float(x) if isinstance(x, np.floating) else str(x))

In [21]:
#full breakdown of returned items
#upper and lower ids are the patient ids of the people above and below the threshold
#target ids is the list of people with a 1 in the thing we're predicting
for k,v in test_rules[0].items():
    print(k)
    print(v)
    print()

features
['V35_Thyroid_cartilage', 'V20_Brainstem', 'max_dose_Brainstem']

thresholds
[np.float64(50.0), np.float64(17.0), np.float64(2977.0)]

info
0.043844526073811924

odds_ratio
1.9967320261437906

lower_count
235

lower_tp
75

lower_mean
0.3191489361702128

upper_count
102

upper_tp
65

upper_mean
0.6372549019607843

upper_ids
['STIEFEL_24', 'STIEFEL_26', 'STIEFEL_34', 'STIEFEL_36', 'STIEFEL_38', 'STIEFEL_42', 'STIEFEL_54', 'STIEFEL_55', 'STIEFEL_66', 'STIEFEL_80', 'STIEFEL_83', 'STIEFEL_85', 'STIEFEL_89', 'STIEFEL_90', 'STIEFEL_91', 'STIEFEL_93', 'STIEFEL_98', 'STIEFEL_101', 'STIEFEL_109', 'STIEFEL_127', 'STIEFEL_1477', 'STIEFEL_1480', 'STIEFEL_149', 'STIEFEL_160', 'STIEFEL_164', 'STIEFEL_165', 'STIEFEL_180', 'STIEFEL_1486', 'STIEFEL_186', 'STIEFEL_193', 'STIEFEL_207', 'STIEFEL_208', 'STIEFEL_213', 'STIEFEL_219', 'STIEFEL_234', 'STIEFEL_238', 'STIEFEL_244', 'STIEFEL_245', 'STIEFEL_248', 'STIEFEL_253', 'STIEFEL_255', 'STIEFEL_298', 'STIEFEL_301', 'STIEFEL_343', 'STIEFEL_347', 'STIEFEL_355', 'STIEFEL_358', 'STIEFEL_360', 'STIEFEL_368', 'STIEFEL_378', 'STIEFEL_380', 'STIEFEL_387', 'STIEFEL_405', 'STIEFEL_1507', 'STIEFEL_1509', 'STIEFEL_420', 'STIEFEL_427', 'STIEFEL_432', 'STIEFEL_436', 'STIEFEL_1525', 'STIEFEL_522', 'STIEFEL_531', 'STIEFEL_1530', 'STIEFEL_554', 'STIEFEL_1535', 'STIEFEL_566', 'STIEFEL_611', 'STIEFEL_616', 'STIEFEL_617', 'STIEFEL_626', 'STIEFEL_651', 'STIEFEL_664', 'STIEFEL_668', 'STIEFEL_696', 'STIEFEL_701', 'STIEFEL_709', 'STIEFEL_716', 'STIEFEL_722', 'STIEFEL_724', 'STIEFEL_731', 'STIEFEL_755', 'STIEFEL_809', 'STIEFEL_855', 'STIEFEL_865', 'STIEFEL_867', 'STIEFEL_878', 'STIEFEL_885', 'STIEFEL_909', 'STIEFEL_932', 'STIEFEL_965', 'STIEFEL_1009', 'STIEFEL_1068', 'STIEFEL_1396', 'STIEFEL_1421', 'STIEFEL_1423', 'STIEFEL_1432', 'STIEFEL_257', 'STIEFEL_469', 'STIEFEL_525', 'STIEFEL_760', 'STIEFEL_1030', 'STIEFEL_1090']

lower_ids
['STIEFEL_28', 'STIEFEL_45', 'STIEFEL_47', 'STIEFEL_60', 'STIEFEL_65', 'STIEFEL_70', 'STIEFEL_73', 'STIEFEL_76', 'STIEFEL_78', 'STIEFEL_87', 'STIEFEL_88', 'STIEFEL_94', 'STIEFEL_95', 'STIEFEL_99', 'STIEFEL_103', 'STIEFEL_105', 'STIEFEL_108', 'STIEFEL_110', 'STIEFEL_112', 'STIEFEL_118', 'STIEFEL_121', 'STIEFEL_122', 'STIEFEL_128', 'STIEFEL_132', 'STIEFEL_137', 'STIEFEL_141', 'STIEFEL_147', 'STIEFEL_148', 'STIEFEL_151', 'STIEFEL_152', 'STIEFEL_153', 'STIEFEL_156', 'STIEFEL_157', 'STIEFEL_158', 'STIEFEL_161', 'STIEFEL_167', 'STIEFEL_170', 'STIEFEL_171', 'STIEFEL_173', 'STIEFEL_175', 'STIEFEL_183', 'STIEFEL_189', 'STIEFEL_202', 'STIEFEL_206', 'STIEFEL_212', 'STIEFEL_215', 'STIEFEL_217', 'STIEFEL_225', 'STIEFEL_229', 'STIEFEL_235', 'STIEFEL_239', 'STIEFEL_243', 'STIEFEL_247', 'STIEFEL_264', 'STIEFEL_265', 'STIEFEL_266', 'STIEFEL_267', 'STIEFEL_272', 'STIEFEL_281', 'STIEFEL_283', 'STIEFEL_292', 'STIEFEL_300', 'STIEFEL_305', 'STIEFEL_307', 'STIEFEL_314', 'STIEFEL_319', 'STIEFEL_321', 'STIEFEL_326', 'STIEFEL_331', 'STIEFEL_336', 'STIEFEL_340', 'STIEFEL_350', 'STIEFEL_351', 'STIEFEL_356', 'STIEFEL_367', 'STIEFEL_372', 'STIEFEL_373', 'STIEFEL_381', 'STIEFEL_384', 'STIEFEL_385', 'STIEFEL_392', 'STIEFEL_394', 'STIEFEL_400', 'STIEFEL_404', 'STIEFEL_409', 'STIEFEL_411', 'STIEFEL_413', 'STIEFEL_415', 'STIEFEL_1508', 'STIEFEL_417', 'STIEFEL_418', 'STIEFEL_422', 'STIEFEL_423', 'STIEFEL_1512', 'STIEFEL_429', 'STIEFEL_444', 'STIEFEL_445', 'STIEFEL_449', 'STIEFEL_451', 'STIEFEL_458', 'STIEFEL_463', 'STIEFEL_1518', 'STIEFEL_491', 'STIEFEL_503', 'STIEFEL_510', 'STIEFEL_511', 'STIEFEL_1528', 'STIEFEL_528', 'STIEFEL_532', 'STIEFEL_533', 'STIEFEL_542', 'STIEFEL_545', 'STIEFEL_547', 'STIEFEL_550', 'STIEFEL_555', 'STIEFEL_567', 'STIEFEL_569', 'STIEFEL_570', 'STIEFEL_575', 'STIEFEL_580', 'STIEFEL_584', 'STIEFEL_586', 'STIEFEL_588', 'STIEFEL_589', 'STIEFEL_600', 'STIEFEL_605', 'STIEFEL_612', 'STIEFEL_614', 'STIEFEL_624', 'STIEFEL_625', 'STIEFEL_629', 'STIEFEL_630', 'STIEFEL_631', 'STIEFEL_1542', 'STIEFEL_636', 'STIEFEL_642', 'STIEFEL_644', 'STIEFEL_648', 'STIEFEL_650', 'STIEFEL_652', 'STIEFEL_661', 'STIEFEL_667', 'STIEFEL_676', 'STIEFEL_683', 'STIEFEL_699', 'STIEFEL_710', 'STIEFEL_711', 'STIEFEL_715', 'STIEFEL_717', 'STIEFEL_723', 'STIEFEL_725', 'STIEFEL_729', 'STIEFEL_749', 'STIEFEL_751', 'STIEFEL_756', 'STIEFEL_1558', 'STIEFEL_761', 'STIEFEL_793', 'STIEFEL_794', 'STIEFEL_1563', 'STIEFEL_798', 'STIEFEL_801', 'STIEFEL_805', 'STIEFEL_1564', 'STIEFEL_828', 'STIEFEL_830', 'STIEFEL_839', 'STIEFEL_842', 'STIEFEL_843', 'STIEFEL_847', 'STIEFEL_882', 'STIEFEL_884', 'STIEFEL_886', 'STIEFEL_887', 'STIEFEL_919', 'STIEFEL_936', 'STIEFEL_948', 'STIEFEL_949', 'STIEFEL_950', 'STIEFEL_955', 'STIEFEL_966', 'STIEFEL_967', 'STIEFEL_971', 'STIEFEL_973', 'STIEFEL_1008', 'STIEFEL_1013', 'STIEFEL_1033', 'STIEFEL_1036', 'STIEFEL_1041', 'STIEFEL_1045', 'STIEFEL_1046', 'STIEFEL_1052', 'STIEFEL_1055', 'STIEFEL_1067', 'STIEFEL_1080', 'STIEFEL_1087', 'STIEFEL_1088', 'STIEFEL_1102', 'STIEFEL_1105', 'STIEFEL_1112', 'STIEFEL_1406', 'STIEFEL_1409', 'STIEFEL_1435', 'STIEFEL_1441', 'STIEFEL_155', 'STIEFEL_222', 'STIEFEL_261', 'STIEFEL_299', 'STIEFEL_1501', 'STIEFEL_439', 'STIEFEL_483', 'STIEFEL_523', 'STIEFEL_572', 'STIEFEL_1545', 'STIEFEL_891', 'STIEFEL_912', 'STIEFEL_956', 'STIEFEL_958', 'STIEFEL_997', 'STIEFEL_1024', 'STIEFEL_1035', 'STIEFEL_1572', 'STIEFEL_1042', 'STIEFEL_1050', 'STIEFEL_2403', 'STIEFEL_1069', 'STIEFEL_1086', 'STIEFEL_1100', 'STIEFEL_1106', 'STIEFEL_1576', 'STIEFEL_1115', 'STIEFEL_1118', 'STIEFEL_1120', 'STIEFEL_1126', 'STIEFEL_1130']

recall
0.4642857142857143

precision
0.6372549019607843

f1
0.5371900826446281

roc_auc
0.6382342277012328

roc_auc_symptom
0.6382342277012328

f1_symptom
0.5371900826446281

target_ids
['STIEFEL_24', 'STIEFEL_26', 'STIEFEL_42', 'STIEFEL_54', 'STIEFEL_60', 'STIEFEL_66', 'STIEFEL_80', 'STIEFEL_85', 'STIEFEL_88', 'STIEFEL_89', 'STIEFEL_91', 'STIEFEL_98', 'STIEFEL_101', 'STIEFEL_103', 'STIEFEL_105', 'STIEFEL_109', 'STIEFEL_110', 'STIEFEL_118', 'STIEFEL_132', 'STIEFEL_1480', 'STIEFEL_149', 'STIEFEL_151', 'STIEFEL_158', 'STIEFEL_161', 'STIEFEL_164', 'STIEFEL_175', 'STIEFEL_1486', 'STIEFEL_186', 'STIEFEL_207', 'STIEFEL_225', 'STIEFEL_234', 'STIEFEL_238', 'STIEFEL_244', 'STIEFEL_245', 'STIEFEL_248', 'STIEFEL_253', 'STIEFEL_255', 'STIEFEL_264', 'STIEFEL_281', 'STIEFEL_283', 'STIEFEL_292', 'STIEFEL_298', 'STIEFEL_319', 'STIEFEL_326', 'STIEFEL_336', 'STIEFEL_347', 'STIEFEL_350', 'STIEFEL_351', 'STIEFEL_355', 'STIEFEL_356', 'STIEFEL_358', 'STIEFEL_367', 'STIEFEL_373', 'STIEFEL_378', 'STIEFEL_385', 'STIEFEL_387', 'STIEFEL_392', 'STIEFEL_1507', 'STIEFEL_413', 'STIEFEL_429', 'STIEFEL_432', 'STIEFEL_436', 'STIEFEL_451', 'STIEFEL_463', 'STIEFEL_1518', 'STIEFEL_1525', 'STIEFEL_510', 'STIEFEL_511', 'STIEFEL_1528', 'STIEFEL_522', 'STIEFEL_531', 'STIEFEL_532', 'STIEFEL_545', 'STIEFEL_554', 'STIEFEL_589', 'STIEFEL_605', 'STIEFEL_611', 'STIEFEL_612', 'STIEFEL_614', 'STIEFEL_616', 'STIEFEL_617', 'STIEFEL_624', 'STIEFEL_626', 'STIEFEL_630', 'STIEFEL_648', 'STIEFEL_650', 'STIEFEL_651', 'STIEFEL_664', 'STIEFEL_676', 'STIEFEL_696', 'STIEFEL_701', 'STIEFEL_709', 'STIEFEL_710', 'STIEFEL_711', 'STIEFEL_715', 'STIEFEL_716', 'STIEFEL_717', 'STIEFEL_722', 'STIEFEL_723', 'STIEFEL_724', 'STIEFEL_731', 'STIEFEL_751', 'STIEFEL_1564', 'STIEFEL_847', 'STIEFEL_855', 'STIEFEL_865', 'STIEFEL_867', 'STIEFEL_878', 'STIEFEL_882', 'STIEFEL_884', 'STIEFEL_885', 'STIEFEL_909', 'STIEFEL_932', 'STIEFEL_948', 'STIEFEL_955', 'STIEFEL_971', 'STIEFEL_973', 'STIEFEL_1045', 'STIEFEL_1068', 'STIEFEL_1080', 'STIEFEL_1409', 'STIEFEL_1421', 'STIEFEL_1435', 'STIEFEL_1441', 'STIEFEL_155', 'STIEFEL_257', 'STIEFEL_261', 'STIEFEL_469', 'STIEFEL_523', 'STIEFEL_1545', 'STIEFEL_760', 'STIEFEL_912', 'STIEFEL_956', 'STIEFEL_958', 'STIEFEL_1030', 'STIEFEL_1042', 'STIEFEL_1050', 'STIEFEL_1086', 'STIEFEL_1090', 'STIEFEL_1100']